package org.mozilla.focus.telemetry

const val EVENT_TAKE_SCREENSHOT = "ky29gk"
const val EVENT_ENTER_PRIVATE_MODE = "dccqsh"
const val EVENT_SAVE_BOOKMKARK = "sj5vxj"
const val EVENT_ADD_TO_HOMESCREEN = "g1tpbz"
const val EVENT_SET_DEFAULT_BROWSER = "iyqe7a"
const val EVENT_SHARE_APP = "3obefy"
const val EVENT_FEEDBACK_POSITIVE = "uivfof"
const val EVENT_CLICK_AFFILIATE_LINK = "6wi26h"
const val EVENT_START_SEARCH = "gobenk"
const val EVENT_GET_VPN = "5cfv22"
const val EVENT_START_CONTENT_TAB = "vi0mil"
const val EVENT_START_TAB_SWIPE_PROCESS = "g3rfhu"
const val EVENT_START_VERTICAL_PROCESS = "sg1h39"